import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { Modal } from "@/components/modal";

const geistSans = JetBrains_Mono({
  weight: ["100", "200", "300", "400", "500", "700", "800"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} flex justify-between bg-slate-100`}
      >
        <Sidebar className="h-screen" />
        <div className="flex-1 p-2 h-screen">
          <div className="h-full bg-white border rounded-lg flex">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
